adobe/aio-cli-plugin-runtime

src/commands/runtime/activation/list.js
test/commands/runtime/activation/list.test.js

https://github.com/apache/incubator-openwhisk-cli/releases/tag/0.10.0-incubating
Particularly enhanced columnar output in activation list
unit tests and code coverage

ACNA-283 - Integrate changes from latest version of wsk cli

---

package.json
src/commands/runtime/deploy/undeploy.js
src/runtime-helpers.js
test/__fixtures__/deploy/deployment_dependencies.yaml
test/__fixtures__/deploy/manifest_dep_dependencies.yaml
test/__fixtures__/deploy/manifest_dependencies.yaml
test/__fixtures__/deploy/manifest_dependencies_error.yaml
test/__fixtures__/deploy/manifest_webSequence.yaml
test/commands/runtime/deploy/index.test.js
test/commands/runtime/deploy/undeploy.test.js

Support for shared actions in a sequence.
The following in a manifest was not working earlier but will work now with deploy command.
packages:
mypackage:
sequences:
authenticate:
actions: '/sharednamespace/sharedpackage/login'
web: 'yes'
Closes #27

ACNA-348 - Shared actions in a sequence

---

src/commands/runtime/action/list.js
test/__fixtures__/action/list-name-sort-output.txt
test/__fixtures__/action/list-name-sort.json
test/commands/runtime/action/list.test.js

add --namesort flag to command action and subcommand list
added a flag to sort names in alphabetical order, otherwise you get our default
`aio runtime action list --namesort`

[ACNA-473][action:list] support `--name-sort` Flag 

---

.github/workflows/nodejs.yml
README.md
src/commands/runtime/activation/logs.js
test/commands/runtime/activation/logs.test.js

Logs --last to see the most recent activations log output

added --last/-l flags to view last log, also shortcut `aio rt log -l`

---

README.md
src/commands/runtime/action/list.js
src/commands/runtime/namespace/get.js
src/commands/runtime/package/list.js
src/commands/runtime/rule/list.js
test/__fixtures__/namespace/get-name-sort.json
test/__fixtures__/namespace/get-name-sort.txt
test/commands/runtime/namespace/get.test.js

aio runtime:namespace:get --name-sort 
Flags:
-n, --name-sort   sorts a list alphabetically by entity name; only applicable within the limit/skip returned entity block

[ACNA-190] [namespace:get] support  --name-sort flag

---

src/commands/runtime/deploy/undeploy.js
test/__fixtures__/deploy/api_manifest.yaml
test/commands/runtime/deploy/undeploy.test.js

Currently crashing when undeploying a manifest with api definitions
This is a fix for it

fix undeploy api

---

README.md
src/commands/runtime/activation/get.js
src/commands/runtime/activation/result.js
test/commands/runtime/activation/get.test.js
test/commands/runtime/activation/logs.test.js
test/commands/runtime/activation/result.test.js

Add --last flag to get/result activation calls

---

package.json
src/commands/runtime/deploy/undeploy.js
src/runtime-helpers.js

Expose the aio runtime plugin helpers as a lib so that they can be reused by the cna scripts/plugin

Expose aio runtime plugin helpers

---

src/commands/runtime/deploy/sync.js
src/commands/runtime/deploy/undeploy.js
src/runtime-helpers.js
test/commands/runtime/deploy/sync.test.js

**is dependency for** https://github.com/adobe/aio-app-scripts/pull/24
modularize and expose the sync logic and get entities (for project removal) to the runtime helpers api.
no added tests as this is mostly code move

expose project deploy and get entities api

---

.gitignore
src/commands/runtime/activation/common.js
src/commands/runtime/activation/get.js
src/commands/runtime/activation/logs.js
test/commands/runtime/activation/get.test.js
test/commands/runtime/activation/logs.test.js

Also corrects a bug in the regex for stripping the log prefix of the form
```
timestamp stream: log-line
```
so that only the `log-line` is printed.
Update .gitignore to include dirty files generated by emacs.
Closes #62.

Implement --logs for activation get.

---

src/commands/runtime/package/create.js
src/commands/runtime/package/update.js
test/commands/runtime/package/create.test.js
test/commands/runtime/package/update.test.js

When using package create/update, omit the parameters and annotation fields unless specified explicitly. This avoid overwriting previously saved values.
Closes #77.

Omit parameters and annotations unless specified for package create/update.

---

src/commands/runtime/action/get.js
test/commands/runtime/action/get.test.js

Proposes fix for #67. The namespace is derived from the action API response instead of wskprops.
Opened issue #67.

Resolve namespace for web action url from the action metadata.

---

src/commands/runtime/action/delete.js

Allows action delete to accept an apihost and auth key.
Closes #86.

Accept base runtime flags.

---

src/commands/runtime/action/create.js

change overloaded P flag to E

---

README.md
package.json

Closes #126 
npm install
npm run prepack

fix: code file links on README.md are broken (/blob/v1.4.0/ not found)

---

src/commands/runtime/trigger/fire.js
test/commands/runtime/trigger/fire.test.js

Pass parameters to trigger fire

---

package.json

For use with `np` or `npm publish`
Prevents publish errors (hopefully).

Add publishConfig access=public to package.json

---

e2e/e2e.js

use actual fs for e2e test

---

src/commands/runtime/activation/logs.js
test/commands/runtime/activation/logs.test.js

Handle case where we do not receive any logs back

---

package.json
src/commands/runtime/action/invoke.js
test/commands/runtime/action/invoke.test.js

Update ow client

---

test/__fixtures__/deploy/manifest_params.yml
test/commands/runtime/deploy/index.test.js

Clearer tests for params using env vars

Clearer tests

---

package.json
src/runtime-helpers.js
test/commands/runtime/deploy/index.test.js

tested manually against an headless app => works

Headless adobe auth validation

---

src/runtime-helpers.js
test/commands/runtime/deploy/sync.test.js

Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/171

fix for package annotations in sync command

---

src/commands/runtime/package/create.js
src/commands/runtime/package/update.js
src/commands/runtime/rule/create.js
src/commands/runtime/rule/update.js
src/commands/runtime/trigger/create.js
src/commands/runtime/trigger/update.js
test/commands/runtime/package/create.test.js

There is a lot of duplicate code in create and update commands.
I see a couple of instances where a change was done in one but not in the other.
Removed duplicates now.

Update cmds now use create cmds where possible

---

test/commands/runtime/action/create.test.js
test/commands/runtime/action/get.test.js

fix typo thrrtLib => throw

---

test/commands/runtime/action/create.test.js

Fix a typo in a test name, relates to #192

fix typo test name: unknrtLibn -> unknown

---

src/commands/runtime/action/create.js
test/commands/runtime/action/create.test.js
test/commands/runtime/action/update.test.js

Add final annotation when creating web action.

---

src/commands/runtime/route/create.js
test/__fixtures__/route/api_swagger.json
test/commands/runtime/route/create.test.js

Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/181

support for route creation using swagger json

---

src/properties.js
test/RuntimeBaseCommand.test.js

Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/90

Support for inline comments in wskprops

---

src/commands/runtime/activation/logs.js
test/__mocks__/@adobe/aio-lib-runtime.js
test/commands/runtime/activation/logs.test.js

Manifest, package and action level filtering of logs

---

src/commands/runtime/activation/list.js
test/__fixtures__/activation/list-triggers-output.txt
test/commands/runtime/activation/list.test.js

Fix activation list for triggers.

---

src/commands/runtime/action/list.js
src/commands/runtime/activation/list.js
src/commands/runtime/package/list.js
src/commands/runtime/rule/list.js
src/commands/runtime/trigger/list.js
test/commands/runtime/action/list.test.js
test/commands/runtime/activation/list.test.js
test/commands/runtime/package/list.test.js
test/commands/runtime/rule/list.test.js
test/commands/runtime/trigger/list.test.js

Add --count for list operations.

---

src/commands/runtime/action/create.js
test/commands/runtime/action/create.test.js
test/commands/runtime/action/update.test.js

Add web-secure for action create.

---

.github/workflows/on-push-publish-to-npm.yml
.github/workflows/version-bump-publish.yml

Add git actions for npm publish

---

README.md
src/commands/runtime/trigger/delete.js

Wrong description of trigger delete command #204
$ aio rt trigger --help
Running the above command incorrectly returned the below description relating to the delete command.  The current description of the delete command shows "Get a trigger..." instead of "Delete a trigger..."
```
COMMANDS
runtime:trigger:create  Create a trigger for Adobe I/O Runtime
runtime:trigger:delete  Get a trigger for Adobe I/O Runtime
```
This has now been corrected to
```runtime:trigger:delete  Delete a trigger for Adobe I/O Runtime```
The Readme has also been corrected in the runtime:trigger:delete section to the below
```
Delete a trigger for Adobe I/O Runtime
```
and
```
Delete a trigger for Adobe I/O Runtime
```
https://github.com/adobe/aio-cli-plugin-runtime/issues/204
The trigger help command description …

fix: corrected description of trigger delete command in help issue #204

---

src/commands/runtime/activation/logs.js
test/__fixtures__/action/list-name-sort-output.txt
test/__fixtures__/namespace/get-name-sort.txt
test/__fixtures__/namespace/get.txt
test/__fixtures__/property/all-empty-wskprops.txt
test/__fixtures__/property/all-server-error.txt
test/__fixtures__/property/all.txt
test/__fixtures__/property/cli-override-wskprops.txt
test/commands/runtime/action/list.test.js
test/commands/runtime/activation/list.test.js
test/commands/runtime/namespace/list.test.js
test/commands/runtime/package/list.test.js
test/commands/runtime/property/get.test.js
test/commands/runtime/rule/list.test.js
test/commands/runtime/trigger/list.test.js

Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/239

No limit at CLI level since this is set by server

---

src/commands/runtime/action/get.js
test/commands/runtime/action/get.test.js

Fix namespace as subdomain get url

---

src/commands/runtime/action/get.js
test/commands/runtime/action/get.test.js

Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/242

fix for undefined version when namespace is subdomain

---

README.md
package.json
src/commands/runtime/namespace/log-forwarding/get.js
src/commands/runtime/namespace/log-forwarding/index.js
src/commands/runtime/namespace/log-forwarding/set.js
src/commands/runtime/namespace/log-forwarding/set/adobe-io-runtime.js
src/commands/runtime/namespace/log-forwarding/set/azure-log-analytics.js
src/commands/runtime/namespace/log-forwarding/set/splunk-hec.js
test/__fixtures__/namespace/log-forwarding/get-remote.json
test/__fixtures__/namespace/log-forwarding/get-result.txt
test/__mocks__/@adobe/aio-lib-runtime.js
test/commands/runtime/namespace/log-forwarding/get.test.js
test/commands/runtime/namespace/log-forwarding/index.test.js
test/commands/runtime/namespace/log-forwarding/set.test.js
test/commands/runtime/namespace/log-forwarding/set/adobe-io-runtime.test.js
test/commands/runtime/namespace/log-forwarding/set/azure-log-analytics.test.js
test/commands/runtime/namespace/log-forwarding/set/splunk-hec.test.js

Added `runtime:namespace:log-forwarding` commands for managing log forwarding settings for the namespace.
- https://github.com/adobe/aio-cli-plugin-runtime/issues/247
- https://github.com/adobe/aio-lib-runtime/pull/70
I/O Runtime is working on configurable Log Forwarding, which will allow a namespace to be configured to custom logs destination. Currently supported: Splunk, Azure Log Analytics. This PR allows logging configuration to be managed via aio CLI.
Auto tests are included.
Also, validated manually on existing I/O Runtime environment with my namespaces.
N/A

Added log forwarding management commands

---

.npmrc
README.md
package.json
src/commands/runtime/property/get.js
test/commands/runtime/property/get.test.js

feat: add proxy support

---

src/commands/runtime/namespace/log-forwarding/index.js

Fixes #252  ( part of it ... there are 2 issues in 1 @moritzraho )

add missing aliases for --help

---

src/commands/runtime/action/get.js
test/commands/runtime/action/get.test.js

By default omit code from the action payload, unless it's explicitly required.
https://github.com/adobe/aio-cli-plugin-runtime/issues/79
unit test.

feat. ACNA-594 - Omit code on action get

---

src/commands/runtime/api/list.js

Fixes #287 
locally linked plugin

fix: ACNA-2103 - cosmetic issue: `api list` was not showing proper `API Name`

---

.github/workflows/daily.yml
.github/workflows/node.js.yml
.github/workflows/on-push-publish-to-npm.yml
.github/workflows/prerelease.yml
.github/workflows/version-bump-publish.yml

Implement reusable github workflows
[ACNA-1833](https://jira.corp.adobe.com/browse/ACNA-1833)
- Code Reusability
- Avoiding Redundancy
- This will be tested after PR is merged and deployed.
- This is workflow changes can only be tested post merge.

ACNA-1833 | Externalising Github Workflows

---

.github/workflows/node.js.yml
src/commands/runtime/action/create.js
test/commands/runtime/action/update.test.js

- Added correct validation for logsize flag as 0 is a valid value
- Unit tests

fix(RUNNER-7199): --logsize action option cannot be set to 0
