- test/commands/runtime/namespace/get.test.js
- test/commands/runtime/route/list.test.js
We had a couple failing tests because travis log output gets truncated differently that what we expect.
Ultimately this was testing the cli-ux table function which should already be tested, we should eventually just mock the call.
> just test for exception, ignore output

- .travis.yml
This is to prevent double builds in PRs.
> Build only master branch, remove osx from build matrix

- package.json
- src/RuntimeBaseCommand.js
- src/commands/runtime/property/get.js
- src/properties.js
- src/runtime-helpers.js
- test/RuntimeBaseCommand.test.js
- test/__fixtures__/property/all-empty-wskprops.txt
- test/jest.setup.js
* use default api_host of https://adobeioruntime.net if api_host is not specified
* clean up debugging namespaces by adding plugin scope
tangentially related to https://github.com/adobe/aio-cli-plugin-runtime/issues/14 but it not a full fix, just a first step
if api host is stable then we can allow it to be an optional.  this wont affect people with open wsk files.
* added test coverage
> add a default api host and clean up some debugging

- src/commands/runtime/activation/index.js
- src/commands/runtime/deploy/index.js
- test/commands/runtime/activation/index.test.js
Also addressed an issue where 'runtime:deploy' when called without flags would error, instead of outputting help like the rest of the sub-commands
> output correct help for runtime:activation when --help flag not present

- package.json
- src/RuntimeBaseCommand.js
- test/RuntimeBaseCommand.test.js
- test/commands/runtime/action/list.test.js
- test/commands/runtime/rule/list.test.js
update openwhisk dep to latest which includes __OW_USER_AGENT env var…, 
add flag to override our default ua
added a flag so this can be overridden, otherwise you get our default
`aio runtime action list --useragent my-user-agent-string`
if an environment var of __OW_USER_AGENT is already present, it will be used, and the flag will be ignored.
flag is hidden, do we want to show it?
manually tested by running with `DEBUG=needle` which shows all whisk api calls
added tests
> [ACNA-290] Set custom useragent for calls to openwhisk rest api

- src/commands/runtime/action/list.js
- src/commands/runtime/namespace/get.js
- src/commands/runtime/package/list.js
- src/commands/runtime/trigger/list.js
- test/commands/runtime/namespace/get.test.js
- test/jest.setup.js
We were skipping some tests because the output varied with different terminals.
This removes whitespace from the equation.
> compare fixture without whitespace

- package.json
memfs@2.16.1 was released that patches the issue.
(this is a dep from jest-plugin-fs)
Closes #59
Cleanup a workaround
npm test
> Remove dep with pin for memfs@2.15.5

- src/commands/runtime/action/create.js
- src/commands/runtime/action/update.js
- src/runtime-helpers.js
- test/__fixtures__/action/get.json
- test/commands/runtime/action/create.test.js
- test/commands/runtime/action/update.test.js
- test/runtime-helpers.test.js
Allows action update without a code artifact.
To address a number of subtleties in the implementation between action create/get and the gap relative to the Apache OpenWhisk CLI (wsk), this patch consolidates the implementation of action create and update so that they are interchangeable.
Summary of changes:
1. action kind determined from file extension
2. disallow action artifact and --sequence
3. dissallow --main on sequence
4. allow update to omit all parameters
5. allow an update to parameters and annotations without replacing code
I have added a number of new tests to cover the changes herein as well.
This PR includes a small patch needed from #69. 
Closes #70.
> Allow action update without a code artifact.

- package.json
- src/commands/runtime/action/create.js
- src/runtime-helpers.js
- test/commands/runtime/action/create.test.js
- test/commands/runtime/action/update.test.js
Use fully qualified names for sequence components during construction of action sequence.
If you accept #72 then a rebased implementation of this patch is available at https://github.com/adobe/aio-cli-plugin-runtime/commit/88ef0a561ea2ff047e2beabf582b34c3c5deca39 and I can PR that instead.
Closes #73.
> Use fully qualified names for sequence components.

- src/commands/runtime/action/get.js
- test/__fixtures__/action/getpackage.json
- test/commands/runtime/action/get.test.js
Save file for package action correctly by stripping package name from filename.
Save file to appropriately named file based on action kind.
Add helpers to map from file names to kinds and vice versa.
Closes #65 .
> Save file to appropriately named file based on action kind ignoring package name.

- src/runtime-helpers.js
currently when deploying an action with an input that points to an undef env variable e.g.:
```
packages:
__APP_PACKAGE__:
license: Apache-2.0
actions:
target:
function: actions/target/index.js
web: 'yes'
runtime: 'nodejs:10'
inputs:
tenant: $TARGET_TENANT --> is not defined
```
the deployment fails with the following error: 
```
ℹ Info: Deploying action [playground-0.0.1/target]...
✖ Deploy actions
OpenWhiskError: PUT https://adobeioruntime.net/api/v1/namespaces/<ns>/actions/<package>/target?overwrite=true Returned HTTP 400 (Bad Request) --> "The request content was malformed:
parameters malformed!"
at Client.handleErrors (~/.nvm/versions/node/v10.15.3/lib/node_modules/@adobe/aio-cli/node_modules/openwhisk/lib/client.js:216:11)
at params.then.catch.err …
```
> fix 400 when undef env vars in manifest

- src/commands/runtime/action/create.js
- test/commands/runtime/action/create.test.js
- test/commands/runtime/action/update.test.js
Base64 encode binary/zip files so they are API compatible. 
This PR also adds a `--binary` flag for files that are not just `.zip` but should be treated the same way.
Closes #85.
Tested against AIO as well as unit tests.
> Base64 encode zip/binary files for action create/update.

- src/commands/runtime/action/get.js
- test/__fixtures__/action/get-package.json
- test/__fixtures__/action/getWebFalse-package.json
- test/commands/runtime/action/get.test.js
Fixes action get --url issues when the action name is fully specified. The implementation now uses the result of action get as the canonical source from which to reconstruct the URL.
Closes https://github.com/adobe/aio-cli-plugin-runtime/issues/94.
> Fix action get --url for fully qualified action name.

- package.json
- src/runtime-helpers.js
Support for deploying single action. In such cases we don’t need to delete junk entities.
When deploying single action we don't want to delete other deployed entities.
manual tests running cli command
- [x ] New feature (non-breaking change which adds functionality)
- [ x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x ] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
> syncProject flag to not delete entities

- src/commands/runtime/activation/list.js
- test/commands/runtime/activation/list.test.js
I added empty checks to `row.annotations` before iterating over it.
The fix covers only the activations, not the actions.
I hit this bug on my environment, and after monkey patching the npm module the issue is fixed.
Therefore I wanted to contribute the fix as PR.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.
> ACNA-625 - Check row.annotations before iterating

- src/runtime-helpers.js
- test/commands/runtime/deploy/index.test.js
Hey! Still learning I/O ins and outs, and went to copy some config in `manifest.yml` to create a second function for my application.
Unfortunately I missed some fields, specifically the `runtime` field. The following error message was flushed when running `aio app deploy`:
```sh
Error: Invalid or missing runtime in the manifest for this action: store-locator-extension-0.0.1/graphql
```
When I read this message, I was thinking of `runtime` more as an Adobe concept, and it didn't immediately occur to me that `runtime` was a _property_ name.
Tweaked two error messages to (hopefully) add some clarity.
Easier onboarding for new folks
Functionality is already covered by unit tests, just updated the error string we're asserting on
> Tweak missing property messages to improve clarity

- src/commands/runtime/action/list.js
- test/commands/runtime/action/list.test.js
* Add the ability to limit the action list by package
#105
It's available in wsk, should be available in aio.
* Added unit test case
* Manual testing
> adding ability to limit action list by package. fixes #105

- src/commands/runtime/activation/logs.js
- test/commands/runtime/activation/logs.test.js
I noticed #95 when working on #107. I made the minimal changes necessary to fix things up.
#95
No promises were being returned in the body of `ActivationLogs.prototype.run`, and  there was no `await` suspending execution of the function, so the `forEach` would finish immediately and `run` would return execution _before_ the calls to `ow.activations.logs` resolved.
Now we're collecting the promises and `await`ing them. If any throw, the `await` will now cause the _first_ error to propagate up the promise chain.
> Fix uncaught async exception warnings in unit tests. Closes #95

- src/commands/runtime/rule/delete.js
- test/__fixtures__/rule/delete.json
- test/commands/runtime/rule/delete.test.js
Adds `--json` to rule delete and emits API response only when flag is present.
Fixes #112.
> Only emit rule delete if json flag is given.

- src/commands/runtime/action/create.js
- test/commands/runtime/action/create.test.js
- test/commands/runtime/action/update.test.js
Enhancement covered by https://github.com/adobe/aio-cli-plugin-runtime/issues/83.
Support -e for adding environment variables on action create/update, binding specified parameters to environment/init variables. The `-e` flag mirrors `-p`.
> Support action create/update -e for adding environment variables to actions.

- package.json
- src/commands/runtime/action/invoke.js
- test/commands/runtime/action/invoke.test.js
This closes two issues, #91 and #101.
1. if the activation request is synchronous but demoted by the backend, the result is an activation id only
2. if the result of the activation is an error response (function returns an error), emit the result and not an error
- #91 
- #101
> Fixes action invoke defects

- src/commands/runtime/action/create.js
- test/commands/runtime/action/create.test.js
- test/commands/runtime/action/update.test.js
This PR supersedes #114 and adds --docker flag for action create/update.
> Support action create/update with --docker.

- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest_docker.yaml
- test/commands/runtime/deploy/index.test.js
The `docker` field in `manifest.yml` is currently ignored. It is needed for deploying blackbox actions. This change sets the right values for the `openwhisk` create action call.
- automatically switch kind to `blackbox` if `docker` is set
- set `image` to value of `docker`
- fix `sequence` type check (now that there is a `blackbox` kind`
#128 
This is required for Nui.
Unit tests. Manual test deployed against actual openwhisk.
n/a
- no doc update needed, using standard feature from wskdeploy manifest, field `docker`: https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_actions.md#fields
> Support deploying of blackbox actions

- src/commands/runtime/trigger/fire.js
Shows trigger activation id when firing a trigger.
```
... trigger fire mytrigger
{
"activationId": "f1f95a6064ed457eb95a6064edf57e78"
}
```
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/121.
> Emit activation id for trigger firing.

- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest_with_adobe_auth.yaml
- test/commands/runtime/deploy/index.test.js
The `require-adobe-auth` allows web actions to be secured using Adobe IMS
This is a temporary implementation that rewrites the target web action to a sequence that first executes the /adobeio/shared-validators/ims validator.
As an example, the following manifest:
```yaml
packages:
helloworld:
actions:
hello:
function: path/to/hello.js
web: 'yes'
require-adobe-auth: true
```
will be deployed as:
```yaml
packages:
helloworld:
actions:
__secured_hello:
function: path/to/hello.js
web: 'yes'
annotations:
require-whisk-auth: true #makes sure action cannot be called by itself anymore
sequences:
hello:
actions: '/adobeio/shared-validators/ims,helloworld/__secured_hello'
```
The annotation will be eventually natively supported by Adobe I/O Runtime, at which point
this PR can be safely reverted.
> require-adobe-auth annotation for web actions in manifest.yaml

- package.json
- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest_with_adobe_auth.yaml
- test/commands/runtime/deploy/index.test.js
The current implementation of require-adobe-auth is not working when multiple actions in the same action use the annotation.
This is a fix for it using lodash.clonedeep.
> fix for multiple actions using the require-adobe-auth annotation in the same package

- src/RuntimeBaseCommand.js
- src/commands/runtime/deploy/index.js
- src/commands/runtime/deploy/sync.js
- src/commands/runtime/deploy/undeploy.js
- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest_with_adobe_auth.yaml
- test/commands/runtime/deploy/index.test.js
- secure original action by making them non web instead of using require-whisk-auth (which allowed every valid namespace to access the action!)
- support for raw-http actions
- only rewrite actions when the  apihost is `adobeioruntime.net`. The current implementation will break other openwhisk deployments such as in a local dev stack. This is because the validation action /adobeio/shared-validators/ims is only available in Adobe I/O Runtime
> harden implementation of require-adobe-auth annotation

- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest_conductor.yaml
- test/commands/runtime/deploy/index.test.js
Added conductor flag support in manifest action annotations deployed via `aio-cli-plugin-runtime`.
Conductor actions make it possible to build and invoke a series of actions, similar to sequences. An action can enabled as a conductor by specifying the conductor annotation:
```
wsk action create myconductor myconductor.js -a conductor true
```
Actions can also be enabled as conductors using a conductor flag in package manifest and when using`wskdeploy`. This PR adds support the same flag support in manifests deployed using `aio-cli-plugin-runtime`.
Below is a sample conductor declaration this PR supports in the manifest.yml file
```
packages:
__APP_PACKAGE__:
license: Apache-2.0
actions:
conductor-action:
function: actions/conductor-action/index.js
runtime: "nodejs:10"
annotations: …
```
> Added conductor flag support to manifest annotations

- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest.yml
> support for ${*} syntax in manifest

- src/commands/runtime/action/invoke.js
- test/commands/runtime/action/invoke.test.js
Add {X-OW-EXTRA-LOGGING: on} header to all action invoke calls from `aio rt`
See issue #146
> add header to invoke for extra logging, this closes #146

- src/commands/runtime/action/list.js
- src/commands/runtime/package/bind.js
- src/commands/runtime/package/delete.js
- src/commands/runtime/package/get.js
- src/runtime-helpers.js
- test/commands/runtime/action/list.test.js
- test/commands/runtime/package/bind.test.js
- test/commands/runtime/package/delete.test.js
- test/commands/runtime/package/get.test.js
Fix issues related to parsing of package name.
Action list, package delete/bind/get now properly parse the package name of
the format [[/]ns/]pkg.
Also fixes --verbose/-v flags on package get.
Closes #123.
> Fix issues related to parsing of package name.

- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest_concurrency.yaml
- test/commands/runtime/deploy/index.test.js
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/176
To discuss: the name choice of `concurrency`. The [openwhisk manifest spec](https://github.com/apache/openwhisk-wskdeploy/blob/master/specification/html/spec_actions.md#valid-limit-keys) does not include it yet (note that `concurrentActivations` is a _different_ limit). I simply used the same name as used in the OpenWhisk API & `wsk`.
- unit test
- deployed example action in production with `concurrency` set in manifest.yml  and tested that `wsk action get <action>` shows the `concurrency` limit
manifest.yml:
```
packages:
__APP_PACKAGE__:
license: Apache-2.0
actions:
worker:
function: actions/worker/index.js
web: 'yes'
runtime: 'nodejs:10'
limits:
concurrency: 42
annotations:
require-adobe-auth: true
```
Result snippet of …
> Support setting action concurrency in manifest #176

- src/commands/runtime/deploy/export.js
- src/commands/runtime/deploy/report.js
- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest.yaml
- test/__fixtures__/deploy/manifest_multiple_packages.yaml
- test/__fixtures__/deploy/report_packages.txt
- test/commands/runtime/deploy/export.test.js
- test/commands/runtime/deploy/index.test.js
- test/commands/runtime/deploy/report.test.js
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/132
Now shared packages can be deployed/undeployed/synced/exported using manifest file.
eg:-
```
packages:
my-package:
public: true
[...]
```
https://github.com/adobe/aio-cli-plugin-runtime/issues/132
> Adding support for shared packages

- src/runtime-helpers.js
- test/__fixtures__/deploy/manifest_conductor.yaml
- test/commands/runtime/deploy/index.test.js
if the `web` action option is set then the conductor annotation is overwritten and ignored.
This is true even if `web: false|no`
From the openwhisk conductor spec: 
> Because a conductor action is an action, it has all the attributes of an action (name, namespace, default parameters, limits...) and it can be managed as such, for instance using the wsk action CLI commands. It can be part of a package or be a web action.
https://github.com/apache/openwhisk/blob/master/docs/conductors.md#conductor-annotation
This PR allows conductor actions to be web
> fix web conductor actions for deploy manifest

- test/commands/runtime/deploy/index.test.js
- test/commands/runtime/deploy/report.test.js
- test/commands/runtime/deploy/undeploy.test.js
Tests for useragent values
Previously tests were hardcoded with version numbers, which broke every release ...
Then this was changed to just test for a string, which is incomplete ...
This tests the value used for useragent is package name + package version
> refactor tests to use useragent value from package.json version

- src/commands/runtime/activation/logs.js
printActionLogs is async (returns a promise) so should be awaited.
This won't matter much in a CLI but when the command is embedded in
another context it can cause the logic of the caller to race ahead of
printing the output.
Closes #209.
> Fix likely error in activation logs logic (#20)

- src/kinds.js
- test/kinds.test.js
This add file/runtime kind recognition for Typescript. While AIO may not support it, it permits the CLI to be used with other deployments. The API server should reject any runtime that is not supported by the deployment.
Closes #211.
> Add typescript kind.

- src/commands/runtime/action/get.js
- test/__fixtures__/action/get.json
- test/commands/runtime/action/get.test.js
When using action get, add a flag `--code` (`-c`) to show the action's code, when the code is in text form.
Additionally, add a global flag that allows action get to show the full action document as JSON when desirable.
Closes #212.
> Add flag to show action code.

- README.md
Updating the installation instructions in the Usage sections of the README to remove -g from the install command as below.  
```diff
-aio plugins:install -g @adobe/aio-cli-plugin-runtime
+aio plugins:install @adobe/aio-cli-plugin-runtime
```
https://github.com/adobe/aio-cli-plugin-runtime/issues/226
Updates readme installation instructions as using ```aio plugins:install -g @adobe/aio-cli-plugin-runtime``` causes an error.  
The update I have made only affects the readme but I ran the unit tests and test/commands/runtime/activation/list.test.js fails which appears to be due to slight difference in received string.  This should not relate to the change I have made in the readme.  
The following test fails which appears to be due to slight difference in string received compared to expected …
> docs: updated usage installation instructions in README.md (issue #226)

- src/commands/runtime/action/invoke.js
- src/commands/runtime/trigger/fire.js
- test/commands/runtime/trigger/fire.test.js
> Fix trigger fire parameters.

- src/commands/runtime/action/list.js
- src/commands/runtime/activation/list.js
- src/commands/runtime/package/list.js
- src/commands/runtime/route/list.js
- src/commands/runtime/rule/list.js
- src/commands/runtime/trigger/list.js
- test/commands/runtime/route/list.test.js
- test/commands/runtime/rule/list.test.js
- test/commands/runtime/trigger/list.test.js
Fixes https://github.com/adobe/aio-cli-plugin-runtime/issues/229
> Better help text for activation limit

- README.md
- src/commands/runtime/activation/logs.js
- test/commands/runtime/activation/logs.test.js
`activation:logs` displays an info message in case custom log forwarding is configured.
In case log forwarding is configured to `adobe_io_runtime`, the behavior stays the same.
https://github.com/adobe/aio-cli-plugin-runtime/issues/260
See https://github.com/adobe/aio-cli-plugin-runtime/issues/260
Manual and auto tests.
> activation:logs: display info message in case custom log forwarding is configured

- src/commands/runtime/activation/list.js
Was testing `activation list --limit=x` for a customer issue in the app-builder channel and realized it was not only spitting out an ugly error, but also actually making the network call if you tried using too large or too small of a value. 
**Before**
```
➜  the-worst-folder git:(main) aio rt activations list --limit=51
›   Error: failed to list the activations: the query parameter 'limit' was malformed:
›   the value '51' is not in the range of 0 to 50 for activations. (400 Bad Request)
›    specify --verbose flag for more information
```
**After**
(Pending oclif/core PR [here](https://github.com/oclif/core/pull/589))
```
➜  the-best-folder git:(main) aio rt activations list --limit=51
Error: Parsing --limit 
Expected an integer less than or equal to 50 but received: 51
See more help …
```
> feat: use oclif min / max for activation list limit flag

- src/commands/runtime/action/create.js
- src/commands/runtime/action/list.js
- src/commands/runtime/activation/list.js
- src/commands/runtime/activation/logs.js
- src/commands/runtime/package/list.js
- src/commands/runtime/rule/list.js
- src/commands/runtime/trigger/list.js
- test/commands/runtime/action/create.test.js
- test/commands/runtime/action/list.test.js
- test/commands/runtime/activation/list.test.js
- test/commands/runtime/activation/logs.test.js
- test/commands/runtime/package/list.test.js
- test/commands/runtime/rule/list.test.js
- test/commands/runtime/trigger/list.test.js
Continuation of https://github.com/adobe/aio-cli-plugin-runtime/pull/270
Figured we should do this for all numeric flags and then cut a release
Closes https://github.com/adobe/aio-cli-plugin-runtime/issues/273
Locally linked plugin, `npm run test`
> feat: use oclif min and max for all numeric flags

- README.md
- src/commands/runtime/namespace/log-forwarding/set/new-relic.js
- test/__mocks__/@adobe/aio-lib-runtime.js
- test/commands/runtime/namespace/log-forwarding/set.test.js
- test/commands/runtime/namespace/log-forwarding/set/new-relic-runtime.test.js
Add New Relic support to log forwarding
- Release of https://github.com/adobe/aio-lib-runtime/pull/148
[Log forwarding New Relic support](https://github.com/adobe/aio-cli-plugin-runtime/issues/310)
[Add New Relic support to aio CLI](https://github.com/adobe/aio-lib-runtime/pull/148)
Log Forwarding currently supports Splunk and Azure Log Analytics. This PR adds support for New Relic.
Auto tests are included
> CEXT-2009 Add New Relic support to aio CLI

- src/commands/runtime/action/create.js
- test/commands/runtime/action/create.test.js
Add a new flag for setting `concurrency` of actions
Default, min, and max taken from [Runtime System Settings](https://developer.adobe.com/runtime/docs/guides/using/system_settings/)
Trying to set concurrency of a blackbox action, which can't be managed with app.config.yaml
Locally linked plugin, `npm run test`
> feat: add concurrency flag to create and update

- src/commands/runtime/action/create.js
- src/commands/runtime/action/list.js
- src/commands/runtime/activation/list.js
- src/commands/runtime/activation/logs.js
- src/commands/runtime/package/list.js
- src/commands/runtime/rule/list.js
- src/commands/runtime/trigger/list.js
- test/commands/runtime/action/create.test.js
- test/commands/runtime/action/list.test.js
- test/commands/runtime/activation/list.test.js
- test/commands/runtime/activation/logs.test.js
- test/commands/runtime/package/list.test.js
- test/commands/runtime/rule/list.test.js
- test/commands/runtime/trigger/list.test.js
Remove client side validation of Openwhisk flag limits. We shouldn't be doing client-side validation for these Openwhisk limits. The errors returned from the server are sufficient enough 
Remove bloat and the need to track these values in multiple places
Locally linked plugin and `npm run test`
> Remove client side validation of Openwhisk flag limits

- README.md
- package.json
closes #332 
1. rm -rf node_modules
2. npm i
3. npm test
4. npm run prepack
5. Inspect README.md for `See code:` links (should point to the `.js` file)
> fix: ACNA-2807 - code links in README point to a .ts file

- package.json
- src/DeployServiceCommand.js
- src/RuntimeBaseCommand.js
- src/commands/runtime/action/create.js
- src/commands/runtime/action/delete.js
- src/commands/runtime/api/create.js
- src/commands/runtime/api/delete.js
- src/commands/runtime/deploy/index.js
- src/commands/runtime/deploy/sync.js
- src/commands/runtime/deploy/undeploy.js
- src/commands/runtime/rule/create.js
- src/commands/runtime/rule/delete.js
- src/commands/runtime/rule/disable.js
- src/commands/runtime/rule/enable.js
- src/commands/runtime/trigger/create.js
- src/commands/runtime/trigger/delete.js
- src/properties.js
- test/DeployServiceCommand.test.js
- test/RuntimeBaseCommand.test.js
- test/commands/runtime/deploy/undeploy.test.js
This PR adds App Builder Deploy Service support for some commands. The Deploy Service requires a user access token (by user login) or a technical account token. The commands are:
- aio rt action create/update/delete/update
- aio api create/delete
- aio rt deploy sync/undeploy
- aio rt rule create/delete/update/disable/enable
- aio rt trigger create/delete/update
You can use Runtime credential basic auth by the `--use-runtime-auth` flag for any of these commands, or set the environment variable `USE_RUNTIME_AUTH=1` to enable it globally. 
Some users use the Runtime plugin as a substitute for the `wsk` cli (since it's a near 1:1 drop-in replacement), so the flag and env var is there to support that scenario.
- npm test
- called all the commands above via the command line with a user login
- …
> breaking-change: ACNA-3833 - add Deploy Service support for some commands

- src/DeployServiceCommand.js
- test/DeployServiceCommand.test.js
In an AB project:
```
❯ aio rt trigger create trigger123
›   Error: failed to create the trigger: Unknown Error From API: [IMSSDK:CONTEXT_NOT_CONFIGURED] IMS context '%s' is
›   not configured
›    specify --verbose flag for more information
```
When the current ims context is not set, you can't get an access token. A truthy check was missing.
- `aio plugins link .` to this PR branch
- delete any ims login via `aio config del ims`
- Go to the root of an AB project
- `aio rt trigger create trigger123`
- should not error
> fix: error when current context is undefined, CLI symbol is undefined
